language: c
services: mongodb
install:
- sudo apt-get install mono-devel mono-gmcs nunit-console
- mozroots --import --sync
script:
- xbuild ./src/Skahal.Infrastructure.Repositories.sln  /p:"DefineConstants=TRAVIS_CI"
- nunit-console ./src/FunctionalTests/bin/Debug/Skahal.Infrastructure.Repositories.FunctionalTests.dll
- nunit-console ./src/Dropbox.FunctionalTests/bin/Debug/Skahal.Infrastructure.Repositories.Dropbox.FunctionalTests.dll
env:
- secure: "LcVkkBBAkOzcpRFd7QedY8GKeCIZzC3ak4L61IYBIwWBR3jAXIQppcvvSty7cocXXG5vyD0Or5AC2mJBvFb/7sPCaIzVdW9b8a5z6tdhWLW894vlFx9TbQR2e1dEchyFCmc3vNXMO0Byjx1ZQRazZHNzOz3mHe1HJ9ejqJvM8+c="
- secure: "A4l0leftHxcez6kRB46BOznmjQERmu9t7u/AZEkPXlXTRarIwkKAIERdwynRYgQyWS8edDgpBXDboGUBn/M69QiO7fUcPN1UrqnQupsuA93BwHYFUkMCD1va4VYkHyRj3YG0nnDYn+zOhQA7TcdmiW0ycDhScDQxy26c/awsCGE="
- secure: "HYK62V1xoBgY1eiRl61D+0G/VmHcQXtIRmE1weEQXX9KgRuPe5MecRwsl4bVtJCDbwsb1sOef5l+gKkuAHgLB79vtDD5NfQ55XGEynwwSb3v60Rb0oAx3pd5kmiykBCghobLuyFbDlscJL1IPiI8+bVWIA1zBOJHZ5Sr3B5Cjxw="