# 
configuration:
  Release

# versioning
version:
  1.0.{build}

# restore nuget packages before build
before_build:
  - nuget restore .\src\Skahal.Infrastructure.Repositories.sln

# build configuration
build:
  verbosity: minimal
